In [10]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options

In [ ]:
import requests
import bs4

In [11]:
profile = Options()
profile.set_preference('browser.download.manager.showWhenStarting', False)

browser = webdriver.Firefox(profile)
browser.get("https://financegpt.uk/basic-analysis/tools/balance-sheet-analysis")

In [12]:
browser.close()

In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('dataset.xlsx')

In [6]:
df

,Unnamed: 0,Полное наименование организации,ИНН,Файл,Данные,Отчёт
0,0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""КОДЕ...",274125308,0710096_0274125308_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN
1,1,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""КОМП...",1001195548,0710096_1001195548_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN
2,2,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ГАРА...",1326147353,0710096_1326147353_2023_001_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN
3,3,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""БИЗН...",1326194113,0710096_1326194113_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN
4,4,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""СПРУ...",1650301536,0710096_1650301536_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN
...,...,...,...,...,...,...
312,312,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ДИСТ...",7826721778,0710099_7826721778_2021_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\n...,NaN
313,313,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЭТНА""",7838000795,0710099_7838000795_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\n...,NaN
314,314,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ИНТЕ...",7838412862,0710099_7838412862_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\n...,NaN
315,315,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ОРАК...",7840304046,0710099_7840304046_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\n...,NaN
316,316,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""САНК...",7841011317,0710099_7841011317_2023_000_20240814.xlsx,Бухгалтерский баланс\t\t\t\t\t\t\t\t\t\t\t\t\n...,NaN

In [ ]:
df

In [7]:
browser.find_element(By.ID, 'i-name').clear()
browser.find_element(By.ID, 'i-name').send_keys(str(df.loc[0, 'Полное наименование организации']))

In [8]:
browser.find_element(By.ID, 'i-content').clear()
browser.find_element(By.ID, 'i-content').send_keys(str(df.loc[0, 'Данные']))

In [9]:
browser.find_element(By.NAME, 'submit').click()

In [13]:
res = WebDriverWait(browser, 120).until(EC.presence_of_element_located((By.ID, 'ai-results')))

In [14]:
field = WebDriverWait(res, 120).until(EC.presence_of_element_located((By.CLASS_NAME, 'card-body')))

In [15]:
field.text

'Анализ бухгалтерского баланса ООО "КОДЕРЛАЙН СОФТ-ПОРТАЛ"\n\nВ соответствии с Международными стандартами финансовой отчетности (МСФО) и Генерально признанными принципами бухгалтерского учета (GAAP), бухгалтерский баланс представляет собой финансовый отчет, отражающий финансовое положение компании на определенную дату.\n\nАнализируя бухгалтерский баланс ООО "КОДЕРЛАЙН СОФТ-ПОРТАЛ" за последние три года, можно отметить следующие ключевые моменты:\n\n1. Активы: Общая стоимость активов компании значительно увеличилась с 23 420 единиц в 2021 году до 60 910 единиц в 2023 году. Это свидетельствует о значительном росте бизнеса. Основной вклад в увеличение активов внесли денежные средства и денежные эквиваленты, а также финансовые и другие оборотные активы.\n\n2. Пассивы: Капитал и резервы компании также значительно увеличились с 8 894 единиц в 2021 году до 43 152 единиц в 2023 году. Это указывает на увеличение собственных средств компании, что является положительным фактором для ее финансовой устойчивости. Кредиторская задолженность также увеличилась, но в меньшей степени.\n\n3. Внеоборотные активы: Материальные внеоборотные активы увеличились, что может свидетельствовать о инвестициях в основные средства или недвижимость. Нематериальные, финансовые и другие внеоборотные активы появились в 2023 году, что может указывать на приобретение нематериальных активов или инвестиций.\n\n4. Оборотные активы: Значительное увеличение оборотных активов, в основном за счет денежных средств и денежных эквивалентов, а также финансовых и других оборотных активов, указывает на увеличение ликвидности компании.\n\nВ целом, финансовое положение ООО "КОДЕРЛАЙН СОФТ-ПОРТАЛ" улучшилось за последние три года. Однако необходимо провести более глубокий анализ, чтобы выявить возможные риски и определить долгосрочную устойчивость компании.'

In [16]:
'''
НЕ СТИРАТЬ, ПАРСЕР ФИН ГПТ
'''
from time import sleep
from tqdm.notebook import tqdm
for i in tqdm(range(df.shape[0])):
    browser.find_element(By.ID, 'i-name').clear()
    browser.find_element(By.ID, 'i-name').send_keys(str(df.loc[i, 'Полное наименование организации']))
    browser.find_element(By.ID, 'i-content').clear()
    browser.find_element(By.ID, 'i-content').send_keys(str(df.loc[i, 'Данные']))
    sleep(1)
    browser.find_element(By.NAME, 'submit').click()
    res = WebDriverWait(browser, 120).until(EC.presence_of_element_located((By.ID, 'ai-results')))
    field = WebDriverWait(res, 120).until(EC.presence_of_element_located((By.CLASS_NAME, 'card-body')))
    df.loc[i,'Отчёт'] = field.text
    print(df.loc[i])

  0%|          | 0/317 [00:00<?, ?it/s]

KeyboardInterrupt:

In [26]:
browser.find_elements(By.CLASS_NAME, 'download-reports-wrapper')[-1].click()

In [30]:
browser.find_elements(By.CLASS_NAME, 'form-item-checkbox_checkbox')[-4].click()

In [32]:
browser.find_elements(By.CLASS_NAME, 'button_md')[-2].click()

In [58]:
'''
НЕ СТИРАТЬ, ПАРСЕР ФИН ОТЧЁТОВ
'''
from time import sleep
from tqdm.notebook import tqdm
flag=False
for i in tqdm(range(260,df.shape[0])):
    browser.find_element(By.ID, 'search').clear()
    browser.find_element(By.ID, 'search').send_keys(str(df.loc[i, 'Идентификационный номер налогоплательщика'])+Keys.ENTER)
    sleep(2)
    elems = browser.find_elements(By.CLASS_NAME, 'results-search-table-row')
    if len(elems) > 0:
        elems[-1].click()
    else:
        continue
    sleep(2)
    if not flag:
        browser.find_elements(By.CLASS_NAME, 'download-reports-wrapper')[-1].click()
        flag=True
        sleep(2)
    browser.find_elements(By.CLASS_NAME, 'form-item-checkbox_checkbox')[2].click()
    sleep(1)
    wrapper = browser.find_element(By.CLASS_NAME, 'download-reports-footer')
    btn = wrapper.find_element(By.CLASS_NAME, 'button_md')
    coordinates = btn.location_once_scrolled_into_view # returns dict of X, Y coordinates
    browser.execute_script('window.scrollTo({}, {});'.format(coordinates['x'], coordinates['y']))
    sleep(1)
    btn.click()

  0%|          | 0/24185 [00:00<?, ?it/s]

IndexError: list index out of range

In [59]:
browser.close()

In [4]:
df = pd.read_excel('akkreditatsiya-it-kompanij-na-19-aprelya-2022.xls')

In [5]:
df

,Регистрационный номер,Дата внесения записи,Полное наименование организации,Основной государственный регистрационный номер организации по ЕГРЮЛ,Идентификационный номер налогоплательщика,Дата решения о государственной аккредитации,Номер решения,Дата внесения изменения,"Сведения об изменениях, внесенных в содержащиеся в реестре сведения об аккредитованной организации (при наличии)",Статус
0,1,2008-01-21,Общество с ограниченной ответственностью «ТЛМ ...,1045207810218,5262128494,2008-01-18,№ 3,2021-09-08,NaN,Аннулирована
1,3,2008-01-25,Общество с ограниченной ответственностью «Прог...,1026102584771,6154064277,2008-01-24,№ 6,NaT,NaN,Действует
2,4,2008-01-25,Общество с ограниченной ответственностью «Лест...,1037739527847,7717129716,2008-01-24,№ 7,NaT,NaN,Действует
3,5,2008-01-25,Закрытое акционерное общество «Научно - произв...,1035004462569,5024013262,2008-01-24,№ 8,NaT,NaN,Действует
4,6,2008-01-25,Общество с ограниченной ответственностью «Порт...,1062724039850,2724093028,2008-01-24,№ 9,NaT,NaN,Действует
...,...,...,...,...,...,...,...,...,...,...
24440,26189,2022-04-19,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""1221...",1225200000695,5260481506,2022-04-19,АО-20220419-4225585866-3,NaT,NaN,Действует
24441,26190,2022-04-19,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ОРИО...",1092468017729,2466220319,2022-04-19,АО-20220419-4225757781-3,NaT,NaN,Действует
24442,26191,2022-04-19,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ИНФО...",1173850003018,3811442862,2022-04-19,АО-20220419-4225824176-3,NaT,NaN,Действует
24443,26192,2022-04-19,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""РОСТОК""",1067536045334,7536071775,2022-04-19,АО-20220419-4227599555-3,NaT,NaN,Действует
24444,26193,2022-04-19,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""БАЛАНС""",1167847123124,7816321770,2022-04-19,АО-20220419-4228395187-3,NaT,NaN,Действует

In [6]:
from os import listdir
from os.path import isfile, join
mypath = 'C:\\flame-chaser\\projects\\LLM-playground\\data-excel\\'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

In [7]:
df['ИНН']

KeyError: 'ИНН'

In [64]:
import zipfile

for file in tqdm(onlyfiles):
    with zipfile.ZipFile(mypath+file, 'r') as zip_ref:
        zip_ref.extractall(mypath)

  0%|          | 0/317 [00:00<?, ?it/s]

In [8]:
data = pd.read_excel(mypath+onlyfiles[0],sheet_name=1)

C:\ProgramData\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
data

,Unnamed: 0,Unnamed: 1,ИНН 0274125308,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Форма по КНД,Unnamed: 12,Unnamed: 13,0710096
0,NaN,NaN,КПП 027801001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Форма по ОКУД,NaN,NaN,710001.0
1,Бухгалтерский баланс,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Пояснения1,NaN,NaN,Наименование показателя,NaN,NaN,Код строки,На 31 декабря 2023 года,NaN,На 31 декабря 2022 год,NaN,NaN,На 31 декабря 2021 года,NaN,NaN
3,1,NaN,NaN,2,NaN,NaN,3,4,NaN,5,NaN,NaN,6,NaN,NaN
4,АКТИВ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,,NaN,NaN,Материальные внеоборотные активы2,NaN,NaN,1150,103,NaN,NaN,343,NaN,NaN,519,NaN
6,,NaN,NaN,"Нематериальные, финансовые и другие внеоборотн...",NaN,NaN,1170,174,NaN,NaN,-,NaN,NaN,-,NaN
7,,NaN,NaN,Запасы,NaN,NaN,1210,533,NaN,NaN,153,NaN,NaN,175,NaN
8,,NaN,NaN,Денежные средства и денежные эквиваленты,NaN,NaN,1250,8 535,NaN,NaN,20 395,NaN,NaN,7 870,NaN
9,,NaN,NaN,Финансовые и другие оборотные активы4,NaN,NaN,1230,51 565,NaN,NaN,8 977,NaN,NaN,14 856,NaN
10,,NaN,NaN,БАЛАНС,NaN,NaN,1600,60 910,NaN,NaN,29 868,NaN,NaN,23 420,NaN
11,ПАССИВ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,,NaN,NaN,Капитал и резервы5,NaN,NaN,1300,43 152,NaN,NaN,18 339,NaN,NaN,8 894,NaN
13,,NaN,NaN,Целевые средства,NaN,NaN,1350,-,NaN,NaN,-,NaN,NaN,-,NaN
14,,NaN,NaN,Фонд недвижимого и особо ценного движимого иму...,NaN,NaN,1360,-,NaN,NaN,-,NaN,NaN,-,NaN
15,,NaN,NaN,Долгосрочные заемные средства,NaN,NaN,1410,-,NaN,NaN,-,NaN,NaN,-,NaN
16,,NaN,NaN,Другие долгосрочные обязательства,NaN,NaN,1450,-,NaN,NaN,-,NaN,NaN,-,NaN
17,,NaN,NaN,Краткосрочные заемные средства,NaN,NaN,1510,-,NaN,NaN,-,NaN,NaN,-,NaN
18,,NaN,NaN,Кредиторская задолженность,NaN,NaN,1520,17 758,NaN,NaN,11 529,NaN,NaN,14 526,NaN
19,,NaN,NaN,Другие краткосрочные обязательства,NaN,NaN,1550,-,NaN,NaN,-,NaN,NaN,-,NaN
20,,NaN,NaN,БАЛАНС,NaN,NaN,1700,60 910,NaN,NaN,29 868,NaN,NaN,23 420,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1 Указывается номер соответствующего пояснения...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
def get_inn(df):
    return int(df.columns[2].split()[-1])

274125308

In [73]:
companies = pd.read_excel('akkreditatsiya-it-kompanij-na-19-aprelya-2022.xls')

In [80]:
companies[companies['Идентификационный номер налогоплательщика'] == 274125308]

,Регистрационный номер,Дата внесения записи,Полное наименование организации,Основной государственный регистрационный номер организации по ЕГРЮЛ,Идентификационный номер налогоплательщика,Дата решения о государственной аккредитации,Номер решения,Дата внесения изменения,"Сведения об изменениях, внесенных в содержащиеся в реестре сведения об аккредитованной организации (при наличии)",Статус
458,504,2010-12-01,Общество с ограниченной ответственностью «Софт...,1080274000487,274125308,2010-12-01,№ 346,NaT,NaN,Действует

In [84]:
result = pd.DataFrame(columns=['Полное наименование организации', 'ИНН', 'Файл', 'Данные', 'Отчёт'])

In [ ]:
for file in